# CI Triggered by a commit in main branch
trigger:
- main

# Use Local Agent to perform the process
pool: 
   name: MiPCAgentPool
   demands:
    - agent.name -equals Agent-WIN-01

variables:
  buildConfiguration: 'Release'

# 1.- Restore dependencies (Nuget Packages)
# 2.- Build solution
steps:
- task: NuGetCommand@2
  displayName: 'dotnet restore'
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'
    feedsToUse: 'select'
- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    command: 'build'
    arguments: '--configuration $(buildConfiguration)'
- task: DotNetCoreCLI@2
  displayName: 'dotnet test'
  inputs:
    command: 'test'
    projects: '**/*Test/*.csproj'
    testRunTitle: 'xUNit Test Run'
  
    