# CI Triggered by a commit in main branch
trigger:
- main

pool: 
   name: MiPCAgentPool
   demands:
    - agent.name -equals Agent-WIN-01

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    arguments: '--configuration $(buildConfiguration)'